* Chapter 4: Threads
    ** Student Lecture 1 [2025-2-24 Mon]
        *** Processes and Threads
          - threads are smaller execution units within a process that allows for parallel executuion
          - processes can have multiple threads execeuting within it 
          - threads share memory with other threads within a process 
          - threads have faster communication and context switching 
          - thread life cycle:
            - new, runnable, running, blocked, waiting, terminated
          - thread creation:
            - created with java 
          - thread sync:
            - mutexes, semaphores, monitors
          - thread pools:
            - manage multiple threads to improve cpu performance
        *** Multithreading
          - multiple threads running within a process to improve CPU utilization
          - makes communication faster between processes
          - single threaded:
            - a process can only do one task at a time, bad efficiency
          - multi threaded:
            - allows a process to perform multiple Tasks
          - advantages:
            - faster to create threads over processes, faster context switching, multiple threads can run, shared memory and resources, etc.
          - disadvantages:
            - increases complexity, difficult debugging and conflicts between threads, too many threads leads to excessive context switching which can reduce performance
        *** Threads
          - user level threads:
            - managed by application, not kernel
            - kernel doesnt see the thread
            - advantages: allows for thread switching without kernel level priveleges, faster since no system calls are needed, portaable
            - disadvantages: system calls are blocking, entire process can get blocked because of one thread causing inefficiency
            - jacketing: a method to convert a blocking system call to a non blocking system call to prevent the entire process from getting blocked
            - writing an application as multiple processes instead as multiple threads: eliminates the advantages of having multiple threads
          - kernel level threads:
            - managed by kernel instead of application, applications use API to interact with the kernel threads, windows uses kernel level threads
            - advantages: parallel execution, better responsiveness, multithreaded kernel which allows for multiple system routines to execute at the same time 
            - disadvantages: high overhead which means that switching requires a mode switch between user and kernel, slower context switching, and higher latency
        *** Multicore and Multithreading
          - uses both user and kernel level threads. allows for improved performance
          - user threads ask kernel threads for system resources, user manages application and kernel threads manage kernel
          - multithreaded native application benefits from this combined approach, so does java, and multiinstance application where there are multiple instances that run
            in parallel
        *** Multithreaded Architecture
          - solaris thread: unix based OS that implements multilevel thread support for scalability, stability, and high performance
          - ULT, LWP, Kernel thread: three level multithreaded architecture made up of user level, lightweight process, and kernel threads
          - LWP data structure: priority, signal mask, registers, stacks, resource usage and profiling data, and pointers
          - state diagram: run, sleep, zombie, blocked, free 
          - interrupts as threads: reduced overhead and increases performance, handled by kernel threads. each interrupt has their own ID, priority, context, and stack
        *** Linux Tasks
            - task_struct: a data structure in linux that represents a process or task. contains information on the following:
                - execution state of a process
                - scheduling information
                - identifiers unique to each process
                - interprocess communication
                - links between processes to the parent processes
                - timers for processes
                - file system that allows for pointers to any files and directories that the process is using 
                - address space that defines addresses assigned to the process
                - processor specific context
            - linux process/thread model:
                - running, running or ready
                - interruptible, blocked state and waiting for an event such as IO or signal from another process
                - uninterruptible, blocked state and waiting directly for hardware conditions, not signals
                - stopped, halted process and can only resume by positive action from another process
                - zombie, process can be terminated but for some reason must have its task structure in the process table
        *** Linux Threads
            - modern unix like linux supports multiple kernel-level threads. 
            - linux treats threads and processes similarly allowing for shared resources like files and memory
            - new processes in linux are created by copying attributes of existing processes using clone() instead of fork(). allows for processes to share 
              resources such as memory, file descriptors, and signal handlers, effectively functioning as threads within a single process. 
            - clone flags:
                - CLONE_NEWPID, creates new process ID namespace 
                - CLONE_PARENT, allows for parent process sharing
                - CLONE_VM, address spaces
                - CLONE_FS, file system state
                - etc.
            - during context switches, if processes share the same address switching is easy. however, cloned processes dont share stacks, meaning for each process
              it needs separate stacks to use
        *** Linux Namespaces
            - namespaces are associated with each process or processes. they are like a way of grouping processes. each group or namespace has a different 
              view of the system. it allows and is important for linux lightweight virtualization, which is a method that allows for processes to believe they 
              are the only processes in the system
            - created by clone() system call, each namespace receives a parameter from the clone flags listed above
            - also created by unshare() which is a call where a process is not created but a new namespace only is created with its attached clone flags
            - namespaces:
                - mount: provides the process with a specific view of the filesystem hierarchy. all file operations that the process does only applies to the
                  filesystem that is visible to the process
                - uts: unix timesharing, related to the uname system call, which provides info about the current kernel like the name (nodename) and network
                  domain (domainname). the domainname is part of the network information service (NIS) which allows for multiple UNIX systems to share common
                  configuration files. allows for easier system administration. important because it allows processes on the same system to have different names
                  and configurations. containerization, where each container has its own hostname and domainname
                - ipc: creates a separate environment for communication resources like sephamores and message queues. processes within the same ipc namespace
                  can communicate with each other, while being isolated from other processes in other namespaces. good for security and containerization to ensure
                  that other apps dont interfere with this IPC's resources. stands for interprocess communication
                - pid: allows for different sets of processes to have the same process ID without conflicts. useful for checkpoint/restore in userspace (CRIU)
                  to freeze a running application and save it to restore it later. CRIU used for process migration, container management, or system recovery either
                  on the same machine or a different one 
                - network: allows for isolation of the system resources associated with networking, each having their own network devices, IP addresses, etc. 
                  allows for process or processes to have access to these network resources, but nothing else
                - user: provide a container with its own set of UID's, separate from the parent allowing for assignment to to a new usernamespace with new PID 
                  namespace and all other namespaces. when a new process is cloned, it can have access to all the resources of the parent process despite being
                  a new process. sensitive security due to creating non priveledged containers
    ** Professor Lecture 1 [2025-2-24 Mon]
      *** Threads
        - useful for running different functions inside a process
        - threads are useful to organize different functions (think about java functions and classes)
        - good for parallel processing 
        - breaks a process into threads, and then each CPU can simultaneously run the thread 
        - benefits of threads in comparison to processes: fast to make, fast to switch, fast to terminate, lower cost to communicate (easier)
        - for processes to communicate, they need to go through the kernel to access the IPC to communicate to another process. however, with threads we can 
          communicate with each other because they share the same memory, things are more control 
    ** Professor Lecture 2 [2025-2-27 Thu]
      *** Threads 
        - processes are not dispatched, threads are dispached now 
        - each thread has a different user stack and kernel stack 
        - in a model for a process, each thread has their own user stack and control stack, along with their own thread control block. the entire process itself has 
          its own process control block too. 
        - threads have their own states too: 
          - running, ready, blocked. 
          - thread operations: spawn block unblock finish
        - history of threads:
          - ULTs (user level threads): kernel only recognizes processes, not threads. many threads to one process (threads to kernel)
        - state model for threads and process:
          - if process wants to make an I/O, kernel blocks, kernel recognizes it because it only recognizes the process, kernel does not change the 
            state of the threads, but everything inluding the threads freezes because the process is no longer getting power from the CPU 
          - the threads maintain their states even when the process is blocked 
          - the thread that is ready first runs next, first come first serve 
          - programmers have control over what thread to run next, it is not in control of the dispatcher
        - jacketing is like a fake system call to prevent blocking of entire process 
        - in KLT, if one thread is blocked the other threads can perform that same blocked process, but KLT is 30 times slower than ULT, but faster to finish processes 
      ** Professor Lecture 3 [2025-3-3 Mon]
        *** Amhdals Law
          - theoretical calculation for speedup (search up the equation) 
          - S, the serial portion cannot be 0 because the processor needs to start with one thread
          - on graphs chart in instructors notes, although threads are good, more processes makes the speedup slower. this is because of syncrhonization, which is 
            when threads can syncrhonize and use the same resources. however with too many threads, there is too much to handle, communication is hard.
        *** Solaris process 
          - unique because it has three levels, userlevel threads, lightweight processes (LWP object), and kernel threads.
          - three characteristics that make OS good: efficient resource manager, good UI for accessibility, and easy to evolve. solaris is good for evolution
          - solaris thread state model: run is ready, and onproc is running 
            - zombie is used so threads can be replaced (housekeeping) dereference the memory and remove everything so that the thread can become -> free state
            - threads are not destroyed, but recycled
            - forces threads to reuse the cache to speed up the response time 
        *** Linux Threads
          - Linux creates tasks, and has group ID's, so it is easy for processes to communicate. however, linux processes iare not fast to make, 
            fast to switch, and fast to terminate.
          - linux only supports tasks, but has threads. it does not distinguish between threads and tasks/processes
        *** Linux Process State Model
          - when process is in the interruptible state, it listens for signals. in the uninterruptible state, it is blocked, only waiting for hardware signals 
        

